# Generated by Django 2.0 on 2017-12-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnSpec',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('animal_id', models.IntegerField()),
                ('flu', models.IntegerField()),
                ('age', models.IntegerField()),
                ('replicate', models.IntegerField()),
                ('tissue', models.CharField(max_length=12)),
            ],
        ),
    ]
